#### PA Assignment 2

In [2]:
# Normalization Problem

import numpy as np

# Create 5x5 ndarray with random values
X = np.random.rand(5, 5)

# Calculate mean and standard deviation
mean_X = X.mean()
std_X = X.std()

# Check for standard deviation to avoid division by zero
if std_X == 0:
    print("Standard deviation is zero, normalization cannot be performed.")
else:
    # Normalize array
    X_normalized = (X - mean_X) / std_X

    # Save normalized array to a .npy file
    np.save('X_normalized.npy', X_normalized)

    # Output: Original and Normalized Array
    print("Original Array:\n", X)
    print("\nNormalized Array:\n", X_normalized)

    # Load and verify the saved normalized array
    loaded_X_normalized = np.load('X_normalized.npy')
    print("\nLoaded Normalized Array from File:\n", loaded_X_normalized)


Original Array:
 [[0.61789604 0.67184561 0.52557368 0.84009505 0.25883287]
 [0.25956534 0.54276179 0.4956852  0.14125323 0.79948448]
 [0.33677567 0.12903058 0.29660405 0.10840156 0.27493186]
 [0.64313878 0.04910352 0.2549344  0.46909685 0.45516488]
 [0.57394061 0.93016544 0.61356249 0.26762854 0.29421605]]

Normalized Array:
 [[ 0.78185509  1.01121235  0.38936261  1.72649569 -0.74463975]
 [-0.74152578  0.46243489  0.26229688 -1.24450921  1.55384689]
 [-0.41327942 -1.29647169 -0.58406212 -1.38417238 -0.67619767]
 [ 0.88917024 -1.63626772 -0.76121342  0.14926116  0.09003178]
 [ 0.5949862   2.10941434  0.76343179 -0.70724648 -0.59421426]]

Loaded Normalized Array from File:
 [[ 0.78185509  1.01121235  0.38936261  1.72649569 -0.74463975]
 [-0.74152578  0.46243489  0.26229688 -1.24450921  1.55384689]
 [-0.41327942 -1.29647169 -0.58406212 -1.38417238 -0.67619767]
 [ 0.88917024 -1.63626772 -0.76121342  0.14926116  0.09003178]
 [ 0.5949862   2.10941434  0.76343179 -0.70724648 -0.59421426]]


In [3]:
# Divisible by 3 Problem

import numpy as np  

# Create 10x10 ndarray of squares of integers from 1 to 100
A = np.arange(1, 101)**2
A = A.reshape((10, 10))  # Reshape into a 10x10 array

# Output: 10x10 array
print("10x10 Array of Squares of the First 100 Positive Integers:\n", A)

# Determine elements divisible by 3 using modulo operation
div_by_3 = A[A % 3 == 0]

# Output: Elements divisible by 3
print("\nElements Divisible by 3:\n", div_by_3)

# Save results to a .npy file
np.save('div_by_3.npy', div_by_3)

# Load and verify the saved array
loaded_div_by_3 = np.load('div_by_3.npy')
print("\nLoaded Elements Divisible by 3 from File:\n", loaded_div_by_3)


10x10 Array of Squares of the First 100 Positive Integers:
 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]

Elements Divisible by 3:
 [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]

Loaded Elements Divisible by 3 from File:
 [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 176