#### PA Assignment 2

In [2]:
# Normalization Problem

import numpy as np

# Create 5x5 ndarray with random values
X = np.random.rand(5, 5)

# Calculate mean and standard deviation
mean_X = X.mean()
std_X = X.std()

# Check for standard deviation to avoid division by zero
if std_X == 0:
    print("Standard deviation is zero, normalization cannot be performed.")
else:
    # Normalize array
    X_normalized = (X - mean_X) / std_X

    # Save normalized array to a .npy file
    np.save('X_normalized.npy', X_normalized)

    # Output: Original and Normalized Array
    print("Original Array:\n", X)
    print("\nNormalized Array:\n", X_normalized)

    # Load and verify the saved normalized array
    loaded_X_normalized = np.load('X_normalized.npy')
    print("\nLoaded Normalized Array from File:\n", loaded_X_normalized)


Original Array:
 [[0.61789604 0.67184561 0.52557368 0.84009505 0.25883287]
 [0.25956534 0.54276179 0.4956852  0.14125323 0.79948448]
 [0.33677567 0.12903058 0.29660405 0.10840156 0.27493186]
 [0.64313878 0.04910352 0.2549344  0.46909685 0.45516488]
 [0.57394061 0.93016544 0.61356249 0.26762854 0.29421605]]

Normalized Array:
 [[ 0.78185509  1.01121235  0.38936261  1.72649569 -0.74463975]
 [-0.74152578  0.46243489  0.26229688 -1.24450921  1.55384689]
 [-0.41327942 -1.29647169 -0.58406212 -1.38417238 -0.67619767]
 [ 0.88917024 -1.63626772 -0.76121342  0.14926116  0.09003178]
 [ 0.5949862   2.10941434  0.76343179 -0.70724648 -0.59421426]]

Loaded Normalized Array from File:
 [[ 0.78185509  1.01121235  0.38936261  1.72649569 -0.74463975]
 [-0.74152578  0.46243489  0.26229688 -1.24450921  1.55384689]
 [-0.41327942 -1.29647169 -0.58406212 -1.38417238 -0.67619767]
 [ 0.88917024 -1.63626772 -0.76121342  0.14926116  0.09003178]
 [ 0.5949862   2.10941434  0.76343179 -0.70724648 -0.59421426]]
